#define WINDOW_BACKGROUND_R 0.086
#define WINDOW_BACKGROUND_G 0.086
#define WINDOW_BACKGROUND_B 0.117
#define WINDOW_BACKGROUND_A 0.5

#define WINDOW_BACKGROUND_DARKER_R WINDOW_BACKGROUND_R
#define WINDOW_BACKGROUND_DARKER_G WINDOW_BACKGROUND_G
#define WINDOW_BACKGROUND_DARKER_B WINDOW_BACKGROUND_B
#define WINDOW_BACKGROUND_DARKER_A 0.9

#define WINDOW_BORDER_R WINDOW_BACKGROUND_R
#define WINDOW_BORDER_G WINDOW_BACKGROUND_G
#define WINDOW_BORDER_B WINDOW_BACKGROUND_B
#define WINDOW_BORDER_A 1

#define LISTBOX_BACKGROUND_R WINDOW_BACKGROUND_R
#define LISTBOX_BACKGROUND_G WINDOW_BACKGROUND_G
#define LISTBOX_BACKGROUND_B WINDOW_BACKGROUND_B
#define LISTBOX_BACKGROUND_A WINDOW_BACKGROUND_A

#define FOCUS_R 1
#define FOCUS_G 1
#define FOCUS_B 1
#define FOCUS_A 1

#define ITEM_NORMAL_R 1
#define ITEM_NORMAL_G 1
#define ITEM_NORMAL_B 1
#define ITEM_NORMAL_A 0.66

#define ITEM_SELECTED_R 1
#define ITEM_SELECTED_G 0.75
#define ITEM_SELECTED_B 0
#define ITEM_SELECTED_A 1

#define ITEM_DISABLED_R 0
#define ITEM_DISABLED_G 0
#define ITEM_DISABLED_B 0
#define ITEM_DISABLED_A 0.66

#define ENTRY_R 1
#define ENTRY_G 1
#define ENTRY_B 1
#define ENTRY_A 1

#define WINDOW_BACKGROUND WINDOW_BACKGROUND_R WINDOW_BACKGROUND_G WINDOW_BACKGROUND_B WINDOW_BACKGROUND_A
#define WINDOW_BACKGROUND_DARKER WINDOW_BACKGROUND_DARKER_R WINDOW_BACKGROUND_DARKER_G WINDOW_BACKGROUND_DARKER_B WINDOW_BACKGROUND_DARKER_A
#define WINDOW_BORDER_COLOUR WINDOW_BORDER_R WINDOW_BORDER_G WINDOW_BORDER_B WINDOW_BORDER_A
#define LISTBOX_BACKGROUND LISTBOX_BACKGROUND_R LISTBOX_BACKGROUND_G LISTBOX_BACKGROUND_B LISTBOX_BACKGROUND_A
#define FOCUS_COLOUR FOCUS_R FOCUS_G FOCUS_B FOCUS_A
#define ITEM_NORMAL ITEM_NORMAL_R ITEM_NORMAL_G ITEM_NORMAL_B ITEM_NORMAL_A
#define ITEM_DISABLED ITEM_DISABLED_R ITEM_DISABLED_G ITEM_DISABLED_B ITEM_DISABLED_A
#define ITEM_SELECTED ITEM_SELECTED_R ITEM_SELECTED_G ITEM_SELECTED_B ITEM_SELECTED_A
#define ENTRY_BOX_COLOUR ENTRY_R ENTRY_G ENTRY_B ENTRY_A
