#include "ui/colours.h"

#define MAIN_WINDOW_OFFSET_X 180
#define MAIN_WINDOW_OFFSET_Y 20
#define MAIN_WINDOW_WIDTH 440
#define MAIN_WINDOW_HEIGHT 380
#define MAIN_WINDOW_RECT MAIN_WINDOW_OFFSET_X MAIN_WINDOW_OFFSET_Y MAIN_WINDOW_WIDTH MAIN_WINDOW_HEIGHT

#define MAIN_CURSOR "ui/assets/3_cursor2"

